spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
  profiles:
    include: oauth